# 多主题目录列表
themes: [landscape,next,light,phase,icarus]
# 多主题服务器端口列表
# 不配置，默认从4001开始
#ports: [5000,5001,5002,5003,5004]

darkmode: 2

path:
  next: /diversity/images/next.jpg
  icarus: /diversity/images/icarus.png

# 主题项目来源【如果没有配置，则主题来源按钮点击无反应】
source:
  next: https://github.com/next-theme/hexo-theme-next
  icarus: https://github.com/ppoffice/hexo-theme-icarus

page:
  header_nav_position: center

back2top:
  enable: true
  enable_scroll_percent: true
  scroll_percent: 3
  position: right
  color: "#fc6423"
  exclude: [next]

font:
  western:
    family: 'Times New Roman, Sitka, Courier New'
  chinese:
    family: '楷体, 等线, 黑体, 宋体, 仿宋'
  nav:
    family: '仿宋'
    size: 17px

comments:
  style: tabs
  active: utterances
  lazyload: true
  nav:
    utterances:
      text: Utterances
      order: 1
    gitalk:
      text: Gitalk
      order: 2
    giscus:
      text: Giscus
      order: 3

utterances:
  enable: true
  repo: huazie/hexo-theme-diversity 
  issue_term: pathname
  theme: github-light
  dark: github-dark

gitalk:
  enable: true
  github_id: huazie
  repo: hexo-theme-diversity
  client_id: Ov23liUeEbTbvL4TtFLI
  client_secret: 625f6af43748eb4a6a27a9111d252155e88c836e
  admin_user: huazie
  distraction_free_mode: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

giscus:
  enable: true
  repo: huazie/hexo-theme-diversity
  repo_id: R_kgDOLxZw-w
  category: Announcements
  category_id: DIC_kwDOLxZw-84CiJXv
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  theme: light
  dark: dark
  input_position: top